### ISSUE TITLE
Question: semicolons between statements

### ISSUE THREAD

**Issue by vanodevium** [Inqnuam/esbuild-plugin-umd-wrapper#2]
There It would be useful to be able to put a semicolon between expressions so that the editor doesn't highlight it as a possible error.

**Comment by vanodevium** [comment]
Clarification: It's not possible error, it's valid error.

**Comment by Inqnuam** [comment]
Thanks for your PR,
Could you please provide a minimal reproductible example

**Comment by vanodevium** [comment]
@Inqnuam 

Of course.
There is [library](https://github.com/dy/sprae/) where this problem I see.

Let me show you the main problem: 
please open [https://unpkg.com/sprae@10.9.3/dist/sprae.umd.js](https://unpkg.com/sprae@10.9.3/dist/sprae.umd.js) and find two lines:
- `if (document?.currentScript?.hasAttribute('init')) sprae(document.documentElement)if (typeof module.exports == "object" && typeof exports == "object") {`
- `}))if (typeof module.exports == "object" && typeof exports == "object") {`

In both cases there is problem with sequence **)if**

**Comment by vanodevium** [comment]
@Inqnuam 

Clarification: while I was looking for a solution, I realized that the first line can be fixed from the side of the library, but the second - **definitely only from the side of the plugin**.

**Comment by vanodevium** [comment]
@Inqnuam 

Please update the version in the npm registry, thanks!

**Comment by Inqnuam** [comment]
should work now
