### ISSUE TITLE
Multiple esbuild.build break the result

### ISSUE THREAD

**Issue by dy** [Inqnuam/esbuild-plugin-umd-wrapper#4]
In [sprae build](https://github.com/dy/sprae/blob/main/.esbuild.js#L35-L39) we found that if we run multiple `esbuild.build` with the plugin multiple times
```js
esbuild.build({
  ...Options,
  minify: true,
  plugins: [umdWrapper({
    libraryName: "sprae"
  })],
})
esbuild.build({
  ...options,
  plugins: [umdWrapper({
    libraryName: "sprae"
  })],
})

```

it produces [broken result](https://github.com/dy/sprae/issues/33#issuecomment-2226827673). It seems tries to wrap the output into UMD twice.

Can you please have a look @Inqnuam

**Comment by Inqnuam** [comment]
Hello @dy

First of all:
- This plugin is only a UMD **Wrapper** around esbuild CJS format,
- This plugin don't transforms your esbuild output bundle into UMD bundle (I think Rollup can do that)

Also I see you are trying to [export](https://github.com/dy/sprae/blob/0ad2499df9795971783ede5846b24ef042e4e9b4/sprae.js#L24) your library with `export default sprae` which will don't work with UMD definition, instead it should be `module.exports = sprae`

I just forked your project, will push a fix soon!

I noticed your request to esbuild author to provide built-in UMD output format, unfortunately I think it will never happen ☹️
